### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by TheQukallon** [radioegor146/jar-to-dll#1]
Я думаю для виндоюзеров будет полезно

**Comment by radioegor146** [comment]
Будет время - сделаю

**Comment by TheQukallon** [comment]
Окей :)

**Comment by radioegor146** [comment]
Просто довольно сложно сделать это адекватно
Много людей будут пытаться юзать эту хрень не так как надо
Вроде выложен скрипт, но нет, всё равно находятся те, кто пытается скомпилить это под MSVC++

**Comment by TheQukallon** [comment]
лол

**Comment by TheQukallon** [comment]
Как по мне, легче через линукс запустить, так как на винде чувствую будут баги и т.д

**Comment by TheQukallon** [comment]
Как я понял в header-converter нужно впихнуть jar?

**Comment by radioegor146** [comment]
Да, pipeline такой:
1. Юзая header-converter.jar делаем classes.h из вашего Jar
2. Далее копируем classes.h в папку с сорсами, и юзая mingw компилим весь проект (main.cpp - большая версия инжекта, main_small.cpp - поменьше)

**Comment by radioegor146** [comment]
fixed
