### ISSUE TITLE
How to inject NetEase

### ISSUE THREAD

**Issue by shimenga** [radioegor146/jar-to-dll#11]

**Comment by a6513375** [comment]
NetEase blocked attach and cannot inject

**Comment by shimenga** [comment]
Can't you inject with hook？

**Comment by a6513375** [comment]
no ican't 
"AttachCurrentThread" was blocked by NetEase , it will cause the game to crash
还有都别用塑料英语了看着我瘆得慌XD

**Comment by a6513375** [comment]
![image](https://user-images.githubusercontent.com/52791712/151278723-32fffcba-22e1-4101-a005-ce64f1f0da9e.png)

**Comment by shimenga** [comment]
谢了
