### ISSUE TITLE
Can't inject it

### ISSUE THREAD

**Issue by uuiddone** [radioegor146/jar-to-dll#15]
1) i tried to inject using process hacker into minecraft process but it doesn't worked
![image](https://github.com/radioegor146/jar-to-dll/assets/155028604/3fe1bd78-b84a-43e6-a8b6-7cae06aa1ea4)
2) i tried with running it too using regsvr32 and it doesn't worked 
![image](https://github.com/radioegor146/jar-to-dll/assets/155028604/5944bcf8-31e1-4ec5-9a99-e94f5cd0e1a1)
![image](https://github.com/radioegor146/jar-to-dll/assets/155028604/cd9ed533-7de9-4d94-b1dd-f2e2b44ea8db)
![image](https://github.com/radioegor146/jar-to-dll/assets/155028604/cee4f5ed-4c34-440b-b016-51b1f3d5f495)

can someone help me in how to inject it into the mc process and what to use? pls

**Comment by uuiddone** [comment]
and i have to know: what i can inject into it? i tried with 1.19.2 forge with the mod sodium and it doesn't injected succesfully, can someone help me?

**Comment by Gatoware-6310** [comment]
its only been tested up to 1.16.5

**Comment by radioegor146** [comment]
> and i have to know: what i can inject into it? i tried with 1.19.2 forge with the mod sodium and it doesn't injected succesfully, can someone help me?

For now, 1.19.2 is probably unsupported
