### ISSUE TITLE
Error installing JDK

### ISSUE THREAD

**Issue by xxxnpno** [radioegor146/jar-to-dll#17]
![image](https://github.com/radioegor146/jar-to-dll/assets/120803617/81e29336-a15e-42fe-ae3f-3111274e6433)

**Comment by radioegor146** [comment]
Can you provide more information? (like press this and send screenshot)
![image](https://github.com/radioegor146/jar-to-dll/assets/16443338/2a4ec724-3728-455b-a807-402c95e51ce5)

**Comment by xxxnpno** [comment]
![image](https://github.com/radioegor146/jar-to-dll/assets/120803617/05208dc2-cea2-45a3-b98e-4c186d2ee27d)
![image](https://github.com/radioegor146/jar-to-dll/assets/120803617/e0d72a36-af35-4011-ac11-f355ad461679)

**Comment by radioegor146** [comment]
Try committing your code again, probably it was temporary issue
