### ISSUE TITLE
Is this a good idea?

### ISSUE THREAD

**Issue by JPeisach** [radioegor146/jar-to-dll#18]
Just saw this in my GitHub feed, and I thought the developer should be aware of [DLL Redirection](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-redirection), that could cause problems with an operating system with malware.

**Comment by radioegor146** [comment]
Yep, I'm aware of this.
In one of the loaders, the dll is unpacked and loaded from random temporary directory.
In other loader, the safety of loading library is directly controlled by JVM (java.library.path).
Either way, the dll is loaded from java runtime, and there are may other ways to use this technique when dealing with Java applications.
Nevertheless, thanks for this issue.

**Comment by radioegor146** [comment]
This tool allows you to make your own dll, that you will need to inject manually, so I don't think that this specific technique is somehow touching this project.
Nevertheless, thank you for the issue.
