### ISSUE TITLE
Винда

### ISSUE THREAD

**Issue by TheQukallon** [radioegor146/jar-to-dll#3]
Еще раз, и да ты фиксанул > 1.7.10 версии, но не винду ))

**Comment by radioegor146** [comment]
Была добавлена полноценная инструкция

**Comment by Avocen** [comment]
А слабо сделать видос как это делать , а то пояснения как в ехаке не понятно

**Comment by radioegor146** [comment]
> А слабо сделать видос как это делать , а то пояснения как в ехаке не понятно

Сделай сам если хочешь. В README.md написана инструкция.

**Comment by radioegor146** [comment]
Т.к. вопрос решён (скоро сделаю решение MSVS), то закрываю issue.
