### ISSUE TITLE
Не робит.

### ISSUE THREAD

**Issue by Avocen** [radioegor146/jar-to-dll#4]
При прописывании в консоли java -jar JavaDllPacker.jar aw classes.h
появляется пустой файл с названием java.

**Comment by radioegor146** [comment]
Приложите консольный вывод.

**Comment by Avocen** [comment]
![Screenshot_106](https://user-images.githubusercontent.com/51483110/60255727-f3abef00-98d8-11e9-99ec-c7810361d13d.png)

**Comment by IgorFgo** [comment]
Таже проблема

**Comment by IgorFgo** [comment]
Только нету такого окна с майн классом

**Comment by radioegor146** [comment]
Хмм, инструкция вроде максимально простая, но нашлись люди которые даже её не смогли прочитать нормально.
В инструкции `вот таким образом` выделена команда, другого копировать не надо.

**Comment by IgorFgo** [comment]
я делал это через старый браузер,через новый оно выделяется

**Comment by Avocen** [comment]
а у меня монитор отсвечивает :D

**Comment by radioegor146** [comment]
Т.к. проблема решена, закрываю issue.
